### ISSUE TITLE
Payment.fns.restrictNumeric is not a function- should it be Payment.restrictNumeric?

### ISSUE THREAD

**Issue by steveTripactions** [zenkkor/ngx-credit-cards#13]
Removed the .fns and it seemed to work on v1.0.9

**Comment by daverickdunn** [comment]
@steveTripactions is very right.

**Payment Object:**

![image](https://user-images.githubusercontent.com/7645242/38997469-698a5ecc-43e5-11e8-9385-82ffa261a6a7.png)

**cc-number-format.directive.js:**

![image](https://user-images.githubusercontent.com/7645242/38997538-94b62b30-43e5-11e8-83d9-1a1649e05669.png)

This applies to **Payment** functions in **cc-cvc-format.directive.js** and **cc-expiry-format.directive.js** as well.
